portfolioproject/myportfolio/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('api/', views.api, name='api'),
    # Define una lista de rutas URL para la aplicación. 
  
    # Ruta para la página de inicio que muestra los proyectos. 
    # URL: '' (vacía), vista: 'index', nombre: 'index'.

    path('contacto/nuevo/', views.contacto_nuevo, name='contacto_nuevo'),
    # Ruta para crear un nuevo contacto. 
    # URL: 'contacto/nuevo/', vista: 'contacto_nuevo', nombre: 'contacto_nuevo'.

    path('contacto/<int:pk>/', views.contacto_detalle, name='contacto_detalle'),
    # Ruta para ver el detalle de un contacto específico.
    # URL: 'contacto/<int:pk>/', vista: 'contacto_detalle', nombre: 'contacto_detalle'.
    # '<int:pk>' es un parámetro que captura un entero (clave primaria).

    path('contacto/<int:pk>/editar/', views.contacto_editar, name='contacto_editar'),
    # Ruta para editar un contacto específico.
    # URL: 'contacto/<int:pk>/editar/', vista: 'contacto_editar', nombre: 'contacto_editar'.

    path('contacto/<int:pk>/eliminar/', views.contacto_eliminar, name='contacto_eliminar'),
    # Ruta para eliminar un contacto específico.
    # URL: 'contacto/<int:pk>/eliminar/', vista: 'contacto_eliminar', nombre: 'contacto_eliminar'.

    path('contactos/', views.contacto_lista, name='contacto_lista'),
    # Ruta para listar todos los contactos.
    # URL: 'contactos/', vista: 'contacto_lista', nombre: 'contacto_lista'.

    path('contacto/confirmacion/', views.contacto_confirmacion, name='contacto_confirmacion'),
    # Ruta para mostrar la confirmación de creación de contacto.
    # URL: 'contacto/confirmacion/', vista: 'contacto_confirmacion', nombre: 'contacto_confirmacion'.

 
    path('vista_protegida/', views.vista_protegida, name='vista_protegida'),  # Nueva URL protegida
   
    path('proyecto/<int:pk>/', views.proyecto_detalle, name='proyecto_detalle'),  # Nueva URL para el detalle del proyecto
]

portfolioproject/portfolioproject/urls.py
from django.conf import settings
# Importa el objeto 'settings' de django.conf para acceder a la configuración del proyecto.

from django.conf.urls.static import static
# Importa la función 'static' de django.conf.urls.static para servir archivos estáticos y de medios en modo de depuración.

from django.contrib import admin
# Importa el módulo 'admin' de django.contrib para habilitar la administración del sitio.

from django.urls import path, include
# Importa las funciones 'path' e 'include' de django.urls para definir rutas URL y incluir otras configuraciones de URLs.

urlpatterns = [
    path('admin/', admin.site.urls),
    # Ruta para la interfaz de administración de Django.
    # URL: 'admin/', vista: 'admin.site.urls'.

    path('', include('myportfolio.urls')),
    # Incluye las rutas URL de la aplicación 'myportfolio'.
    # URL: '', incluye: 'myportfolio.urls'.
      path('accounts/', include('django.contrib.auth.urls')),  ########Añade las vistas de autenticación de Django
      path('ckeditor', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    # Condicional para verificar si el modo de depuración está habilitado.
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # Si el modo de depuración está habilitado, añade las rutas para servir archivos de medios.
    # URL base: settings.MEDIA_URL, directorio raíz de documentos: settings.MEDIA_ROOT.

portfolioproject/myportfolio/models.py
from django.db import models
from ckeditor.fields import RichTextField  #####################ETAPA 5
from .utils import encrypt_message, decrypt_message

class Categoria(models.Model):
    nombre = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.nombre

class Tecnologia(models.Model):
    nombre = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.nombre

class Proyecto(models.Model):
    titulo = models.CharField(max_length=200)
    imagen = models.ImageField(upload_to='proyectos/')
    descripcion = models.TextField()
    contenido = RichTextField()  # Campo de texto enriquecido#######ETAPA 5
    tecnologias = models.ManyToManyField(Tecnologia)
    link_sitio = models.URLField(max_length=200)
    link_repositorio = models.URLField(max_length=200)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)

    def __str__(self):
        return self.titulo

class Contacto(models.Model):
    nombre = models.CharField(max_length=100)
    email = models.EmailField()
    mensaje = models.TextField()  # Campo para el mensaje original
    mensaje_cifrado = models.TextField()  # Campo para almacenar el mensaje cifrado
    fecha = models.DateTimeField(auto_now_add=True)  # Añade el campo de fecha

    def save(self, *args, **kwargs):
        # Cifra el mensaje antes de guardarlo
        self.mensaje_cifrado = encrypt_message(self.mensaje)
        super().save(*args, **kwargs)

    def get_mensaje(self):
        # Descifra el mensaje al recuperarlo
        return decrypt_message(self.mensaje_cifrado)

    def __str__(self):
        return self.nombre

portfolioproject/myportfolio/forms.py
from django import forms
from .models import Contacto

# Definición de un formulario basado en el modelo Contacto
class ContactoForm(forms.ModelForm):
    # Clase interna Meta que contiene la configuración del formulario
    class Meta:
        # Especifica el modelo del cual se creará el formulario
        model = Contacto
        # Define los campos del modelo que se incluirán en el formulario
        fields = ['nombre', 'email', 'mensaje']
        # Especifica los widgets personalizados para los campos del formulario
        widgets = {
            # Utiliza un widget de entrada de texto con una clase CSS 'form-control' para el campo 'nombre'
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
         
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
      
            'mensaje': forms.Textarea(attrs={'class': 'form-control'}),
        }

portfolioproject/myportfolio/views.py
# Importa decoradores y funciones útiles para la autenticación y manejo de vistas
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
# Importa el formulario de contacto y los modelos Proyecto y Contacto de la aplicación actual
from .forms import ContactoForm
from .models import Proyecto, Contacto
# Create your views here.
def home(request):
    proyectos = Proyecto.objects.all()
    return render(request, 'index.html', {'proyectos': proyectos})
    
def api(request):
    return render(request, 'Apiindex.html')

# Vista para la página de inicio que muestra los proyectos


# Vista para crear un nuevo contacto usando un formulario
def contacto_nuevo(request):
    # Si la solicitud es de tipo POST, se procesa el formulario
    if request.method == "POST":
        # Se crea una instancia del formulario con los datos enviados
        form = ContactoForm(request.POST)
        # Si el formulario es válido, se guarda el nuevo contacto
        if form.is_valid():
            form.save()
            # Redirige a una página de confirmación
            return redirect('contacto_confirmacion')
    else:
        # Si la solicitud no es POST, se crea un formulario vacío
        form = ContactoForm()
    # Renderiza la plantilla 'contacto_formulario.html' pasando el formulario como contexto
    return render(request, 'myportfolio/contacto_formulario.html', {'form': form})

 #Crea una vista que mostrará el detalle del proyecto en el archivo views.py 
def proyecto_detalle(request, pk):
    proyecto = get_object_or_404(Proyecto, pk=pk)
    return render(request, 'proyecto_detalle.html', {'proyecto': proyecto})

# Vista para ver el detalle de un contacto específico, requiere autenticación
@login_required
def contacto_detalle(request, pk):
    # Obtiene el contacto con la clave primaria especificada, o retorna 404 si no se encuentra
    contacto = get_object_or_404(Contacto, pk=pk)
    # Renderiza la plantilla 'contacto_detalle.html' pasando el contacto como contexto
    return render(request, 'myportfolio/contacto_detalle.html', {'contacto': contacto})

# Vista para editar un contacto específico, requiere autenticación
@login_required
def contacto_editar(request, pk):
    # Obtiene el contacto con la clave primaria especificada, o retorna 404 si no se encuentra
    contacto = get_object_or_404(Contacto, pk=pk)
    # Si la solicitud es de tipo POST, se procesa el formulario
    if request.method == "POST":
        # Se crea una instancia del formulario con los datos enviados y el contacto existente
        form = ContactoForm(request.POST, instance=contacto)
        # Si el formulario es válido, se guarda el contacto editado
        if form.is_valid():
            form.save()
            # Redirige a la vista de detalle del contacto
            return redirect('contacto_detalle', pk=contacto.pk)
    else:
        # Si la solicitud no es POST, se crea un formulario con los datos del contacto existente
        form = ContactoForm(instance=contacto)
    # Renderiza la plantilla 'contacto_editar.html' pasando el formulario como contexto
    return render(request, 'myportfolio/contacto_editar.html', {'form': form})

# Vista para eliminar un contacto específico, requiere autenticación
@login_required
def contacto_eliminar(request, pk):
    # Obtiene el contacto con la clave primaria especificada, o retorna 404 si no se encuentra
    contacto = get_object_or_404(Contacto, pk=pk)
    # Elimina el contacto
    contacto.delete()
    # Redirige a la vista de lista de contactos
    return redirect('contacto_lista')

# Vista para listar todo0000s los contactos, requiere autenticación
@login_required
def contacto_lista(request):
    # Obtiene todos los objetos de la clase Contacto
    contactos = Contacto.objects.all()
    # Renderiza la plantilla 'contacto_lista.html' pasando los contactos como contexto
    return render(request, 'myportfolio/contacto_lista.html', {'contactos': contactos})

# Vista de confirmación de contacto
def contacto_confirmacion(request):
    # Renderiza la plantilla 'contacto_confirmacion.html'
    return render(request, 'myportfolio/contacto_confirmacion.html')
####################################################################
@login_required
def vista_protegida(request):
    return render(request, 'vista_protegida.html')

portfolioproject/myportfolio/templates/Apiindex.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/apistyles.css' %}">
  <title>API Rick and Morty</title>
</head>
<body>
  <header></header>
  <main>
    <h1>API: Rick and Morty</h1>
    <h3>Bienvenido a la API de Rick and Morty, podrás buscar tus personajes favoritos</h3>
    <a href="{% url 'home' %}" class="btn btn-primary">Atrás</a>
    <hr>
    <input id="txt-character" class="finder-character" type="text" placeholder="Busca tu personaje por su nombre:">
    <div id="containerCards" class="container-cards">
    </div>
  </main>
  <footer>
    <a href="{% url 'home' %}">Gabriel H.</a>
  </footer>
  <script src="{% static 'js/apiscript.js' %}"></script>
</body>
</html>

portfolioproject/myportfolio/templates/base_generic.html
{% load bootstrap5 %}
<!-- Carga las etiquetas de la biblioteca de Django para Bootstrap 5 -->

{% load static %}
<!-- Carga las etiquetas de la biblioteca de Django para archivos estáticos -->

<!DOCTYPE html>
<html lang="en">
<!-- Define el tipo de documento como HTML5 y establece el idioma a inglés -->

<head>
    <meta charset="UTF-8">
    <!-- Define la codificación de caracteres como UTF-8 -->

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Configura la ventana gráfica para que el diseño sea responsive -->

    <title>{% block title %}Mi Portafolio{% endblock %}</title>
    <!-- Define el título del documento, que puede ser sobreescrito en otras plantillas extendidas -->

    {% bootstrap_css %}
    <!-- Inserta las hojas de estilo CSS de Bootstrap 5 -->

    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <!-- Incluye una hoja de estilo CSS personalizada desde los archivos estáticos -->

    {% block extra_head %}
    <!-- Bloque extra para añadir contenido adicional en la cabecera en otras plantillas extendidas -->
    {% endblock %}
</head>

<body>
    {% block content %}
    <!-- Comienza un bloque de contenido que será definido en las plantillas que extiendan esta plantilla -->
    {% endblock %}

    {% bootstrap_javascript %}
    <!-- Inserta los scripts JavaScript de Bootstrap 5 -->

    <script src="{% static 'js/script.js' %}"></script>
    <!-- Incluye un script JavaScript personalizado desde los archivos estáticos -->
</body>
</html>

portfolioproject/myportfolio/templates/index.html
{% load bootstrap5 %}
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js" integrity="sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/easy-pie-chart/2.1.6/jquery.easypiechart.min.js" integrity="sha512-DHNepbIus9t4e6YoMBSJLwl+nnm0tIwMBonsQQ+W9NKN6gVVVbomJs9Ii3mQ+HzGZiU5FyJLdnAz9a63ZgZvTQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.emailjs.com/dist/email.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/estilo.css'%}">
    
    <title>Portafolio</title>
    {% bootstrap_css %}
</head>
<body>
    </section>
    <span class="sombra">
        <section id="inicio" class="inicio">
            <div class="contenido">
                <header>
                    <div class="logo">
                        <a href="#inicio">
                            <img src="{% static 'images/beautiful-anime-landscape-cartoon-scene_23-2151035237.avif' %}"  alt="Logo" class="logo-img">
                           
                        </a>
                        <h1>GH</h1>                        
                    </div>
                    
                    <nav id="nav">
                        
                        <a href="{% url 'api' %}" class="botonrick">API R&M</a>
                        <a href="#inicio">Inicio</a>
                        <a href="#servicios">Servicios</a>
                        <a href="#habilidades">Habilidades</a>
                        <a href="#trabajos">Trabajos</a>
                        <a href="#contacto">Contacto</a>
                    
                    </nav>
    
                    <!-- Icono del menu responsive -->
                    <div id="icono-nav" onclick="responsiveMenu()">
                        <i class="fa-solid fa-bars"></i>
                    </div>
    
                    <div class="redes">
                        <a href="https://www.linkedin.com/in/gabriel-hinostroza-42b18728a/"><i class="fa-brands fa-linkedin"></i></a>
                        <a href="https://www.facebook.com/"><i class="fa-brands fa-facebook"></i></a>
                        <a href="https://www.instagram.com"><i class="fa-brands fa-instagram"></i></a>
                        <a href="https://github.com/GabrielHinostroza2"><i class="fa-brands fa-github"></i></a>
                    </div>
                </header>
    
                <div class="fila">
                    <div class="col">
                        <h2>MI PORTAFOLIO WEB</h2>
                        <p>Esta pagina web, fue construida con HTML, JS, CSS y Boostrap 5. Además contendrá mi CV, información sobre mi, mis habilidades, mis proyectos y un área para contactarme.</p>
                        <a href="https://drive.google.com/file/d/1Hfx_AFuJRAmbWEUKJAUw0HV0d4ik3XOW/view?usp=sharing" class="btn btn-1">Descargar CV</a>

                    </div>
                    <div class="col">
                        <div class="contenedor-img">
                            <img src="{% static 'images/foto-inicio.png' %}" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </span>
    
    
    <!-- sección SERVICIOS -->
    <section id="servicios" class="servicios">
        <div class="fila">
            <div class="col">
                <div class="card bg1">
                    <div class="card">
                        <div class="icono color1">
                            <div class="circulo">
                                <i class="fa-solid fa-circle-info"></i>
                            </div>
                        </div>
                    </div>
                    <h4>Sobre mi</h4>
                    <p>Llevo 2 años estudiando Ingeniería Informática, pero desde pequeño me han apasionado las tecnologías.</p>
                    <a href="https://drive.google.com/file/d/1Hfx_AFuJRAmbWEUKJAUw0HV0d4ik3XOW/view?usp=sharing">Leer Más</a>
                </div>
            </div>
            <div class="col">
                <div class="card bg2">
                    <div class="card">
                        <div class="icono color2">
                            <div class="circulo">
                                <i class="fa-solid fa-wand-magic-sparkles"></i>
                            </div>
                        </div>
                    </div>
                    <h3>Creatividad</h3>
                    <h2>Soy una persona muy creativa cuando la ocasión y momento lo necesita, pero hay situaciones dónde me estanco.</h2>
                </div>
            </div>
            <div class="col">
                <div class="card bg3">
                    <div class="card">
                        <div class="icono color3">
                            <div class="circulo">
                                <i class="fa-solid fa-headset"></i>
                            </div>
                        </div>
                    </div>
                    <h3>Otros</h3>
                    <p>Me gusta jugar videojuegos, escuchar música, ver series o anime. Practico igual deportes como Voleibol y fútbol.</p>
            </div>
        </div>
        
    </section>
    {% load static %}
   <!-- sección habilidades -->
<section class="habilidades" id="habilidades">
    <div class="contenedor-habi">
        <h2>Habilidades</h2>
        <div class="fila">
            <div class="col">
                <div class="score">
                    <div class="box">
                        <div class="chart" data-percent="65">
                            <span>65%</span>
                        </div>
                        <h2>HTML & CSS</h2>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="score">
                    <div class="box">
                        <div class="chart" data-percent="90">
                            <span>90%</span>
                        </div>
                        <h2>ATENCIÓN AL CLIENTE</h2>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="score">
                    <div class="box">
                        <div class="chart" data-percent="65">
                            <span>65%</span>
                        </div>
                        <h2>JAVASCRIPT</h2>
                    </div>
                </div>
            </div>
        </div>
        <div class="fila">
            <div class="col">
                <div class="score">
                    <div class="box">
                        <div class="chart" data-percent="70">
                            <span>70%</span>
                        </div>
                        <h2>SQL DEVELOPER</h2>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="score">
                    <div class="box">
                        <div class="chart" data-percent="90">
                            <span>90%</span>
                        </div>
                        <h2>LIDERAZGO</h2>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="score">
                    <div class="box">
                        <div class="chart" data-percent="70">
                            <span>70%</span>
                        </div>
                        <h2>JAVA</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>



    <!-- Projects Section -->
    <section id="projects" class="py-5">
        <div class="container">
            <h2 class="text-center">My Projects</h2>
            <div class="row">
                {% for proyecto in proyectos %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <img src="{{ proyecto.imagen.url }}" class="card-img-top" alt="{{ proyecto.titulo }}">
                        <div class="card-body">
                            <h5 class="card-title">{{ proyecto.titulo }}</h5>
                            <p class="card-text">{{ proyecto.descripcion }}</p>
                            <a href="{{ proyecto.link_sitio }}" class="btn btn-primary" target="_blank">Web</a>
                            <a href="{{ proyecto.link_repositorio }}" class="btn btn-secondary" target="_blank">Repositorio</a>
                            <a href="{% url 'proyecto_detalle' proyecto.pk %}" class="btn btn-info">Ver Detalle</a> <!-- Nuevo botón -->
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>

 <!-- Contact Section -->
    <section id="contact" class="py-5 bg-light">
        <div class="container">
            <h2 class="text-center">Contáctame</h2>
            <form method="POST" action="{% url 'contacto_nuevo' %}" class="needs-validation" novalidate>
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_nombre" class="form-label">Nombre</label>
                    <input type="text" class="form-control" id="id_nombre" name="nombre" required>
                    <div class="invalid-feedback">Por favor ingresa un nombre.</div>
                </div>
                <div class="mb-3">
                    <label for="id_email" class="form-label">Correo</label>
                    <input type="email" class="form-control" id="id_email" name="email" required>
                    <div class="invalid-feedback">Por favor ingresa un correo.</div>
                </div>
                <div class="mb-3">
                    <label for="id_mensaje" class="form-label">Mensaje</label>
                    <textarea class="form-control" id="id_mensaje" name="mensaje" rows="3" required></textarea>
                    <div class="invalid-feedback">Por favor ingresa un mensaje.</div>
                </div>
                <button type="submit" class="btn btn-primary">Enviar</button>
            </form>
        </div>
    </section>
</body>
</html>

    <footer>
        <p>Creado por Gabriel Hinostroza - 2024 - </p>
    </footer>
    {% bootstrap_javascript %}
    <script src="{% static 'js/app.js' %}"></script>
</body>
</html>

portfolioproject/myportfolio/templates/proyecto_detalle.html
{% extends 'base_generic.html' %}

{% block content %}
  <div class="container mt-5">
    <h2>{{ proyecto.titulo }}</h2>
    <img src="{{ proyecto.imagen.url }}" alt="{{ proyecto.titulo }}" class="img-fluid">
    <p><strong>Descripción:</strong> {{ proyecto.descripcion }}</p>
    <div>
      <h3>Contenido Detallado</h3>
      <div>{{ proyecto.contenido|safe }}</div>  <!-- Usar el filtro 'safe' para permitir HTML -->
    </div>
    <p><strong>Tecnologías:</strong> {{ proyecto.tecnologias.all|join:", " }}</p>
    <a href="{{ proyecto.link_sitio }}" class="btn btn-primary">Sitio Web</a>
    <a href="{{ proyecto.link_repositorio }}" class="btn btn-secondary">Repositorio</a>
  </div>
{% endblock %}